### PR TITLE
Bunch of small formatting and commenting changes

### PR DESCRIPTION
**Pull request by Mingling94**
I should have spread this out into more commits but here's what I did:

- Changed `"` to `'` for consistency's sake.
- Commented a bunch more for my own clarification.
- Changed around some code format and reorganized.
- Renamed certain variables to be more self-evident.

Feel more than free to challenge me on these changes, a lot of changes were made to just be different and aren't necessarily better. I also didn't use jslint and am a jshint user. Let me know if anything I did isn't by jslint standards ^_^

### CODE REVIEW

**Comment by Mingling94** [comment]
Also I asked a few questions in the form of "TODO" comments. Please get back to me, addressing them. Thanks!

**Comment by Mingling94** [comment]
Testing it now, I see a bunch of issues (perhaps pre-existing) that I'll have to debug. Closing the PR for now, but I'd still appreciate a review @acarabott ^_^

**Comment by acarabott** [comment]
Brief look through this, all the consistency work is great, and some of it could be merged in if you can break it out into separate commits?

Could you detail the issues you're seeing? I've had comments from Windows users that have particular issues (i.e. with vertical task bars)

**Comment by Mingling94** [comment]
@acarabott Sorry to have been MIA for a month. Busy busy, though I'll try to redo this PR in separated commits this weekend

**Comment by acarabott** [comment]
No problem, I've got a lot of work on at the moment, but will take a look
when you've done it.


+1 (347) 824 5039
www.arthurcarabott.com

**Pull request closed without merging**
